### ISSUE TITLE
Cannot install webpack due to eslint-scope's folder structure

### ISSUE THREAD

**Issue by qwenger** [amol-/dukpy#56]
I tried installing `webpack` via `dukpy.install_jspackage` but it fails because some dependencies do not have a `package` folder in the .tgz file:

```python
import dukpy

dukpy.install_jspackage("webpack", "5.59.0", "assets_dl/")
```
```
Packages going to be installed: webpack->5.59.0, @types/eslint-scope->3.7.1, @types/eslint->7.28.1, @types/estree->0.0.50, @types/json-schema->7.0.9, @types/estree->0.0.50, @types/estree->0.0.50, @webassemblyjs/ast->1.11.1, @webassemblyjs/helper-numbers->1.11.1, @webassemblyjs/floating-point-hex-parser->1.11.1, @webassemblyjs/helper-api-error->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/wasm-edit->1.11.1, @webassemblyjs/ast->1.11.1, @webassemblyjs/helper-numbers->1.11.1, @webassemblyjs/floating-point-hex-parser->1.11.1, @webassemblyjs/helper-api-error->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/helper-buffer->1.11.1, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/helper-wasm-section->1.11.1, @webassemblyjs/ast->1.11.1, @webassemblyjs/helper-numbers->1.11.1, @webassemblyjs/floating-point-hex-parser->1.11.1, @webassemblyjs/helper-api-error->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/helper-buffer->1.11.1, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/wasm-gen->1.11.1, @webassemblyjs/ast->1.11.1, @webassemblyjs/helper-numbers->1.11.1, @webassemblyjs/floating-point-hex-parser->1.11.1, @webassemblyjs/helper-api-error->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/ieee754->1.11.1, @xtuc/ieee754->1.2.0, @webassemblyjs/leb128->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/utf8->1.11.1, @webassemblyjs/wasm-gen->1.11.1, @webassemblyjs/ast->1.11.1, @webassemblyjs/helper-numbers->1.11.1, @webassemblyjs/floating-point-hex-parser->1.11.1, @webassemblyjs/helper-api-error->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/ieee754->1.11.1, @xtuc/ieee754->1.2.0, @webassemblyjs/leb128->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/utf8->1.11.1, @webassemblyjs/wasm-opt->1.11.1, @webassemblyjs/ast->1.11.1, @webassemblyjs/helper-numbers->1.11.1, @webassemblyjs/floating-point-hex-parser->1.11.1, @webassemblyjs/helper-api-error->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/helper-buffer->1.11.1, @webassemblyjs/wasm-gen->1.11.1, @webassemblyjs/ast->1.11.1, @webassemblyjs/helper-numbers->1.11.1, @webassemblyjs/floating-point-hex-parser->1.11.1, @webassemblyjs/helper-api-error->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/ieee754->1.11.1, @xtuc/ieee754->1.2.0, @webassemblyjs/leb128->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/utf8->1.11.1, @webassemblyjs/wasm-parser->1.11.1, @webassemblyjs/ast->1.11.1, @webassemblyjs/helper-numbers->1.11.1, @webassemblyjs/floating-point-hex-parser->1.11.1, @webassemblyjs/helper-api-error->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/helper-api-error->1.11.1, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/ieee754->1.11.1, @xtuc/ieee754->1.2.0, @webassemblyjs/leb128->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/utf8->1.11.1, @webassemblyjs/wasm-parser->1.11.1, @webassemblyjs/ast->1.11.1, @webassemblyjs/helper-numbers->1.11.1, @webassemblyjs/floating-point-hex-parser->1.11.1, @webassemblyjs/helper-api-error->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/helper-api-error->1.11.1, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/ieee754->1.11.1, @xtuc/ieee754->1.2.0, @webassemblyjs/leb128->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/utf8->1.11.1, @webassemblyjs/wast-printer->1.11.1, @webassemblyjs/ast->1.11.1, @webassemblyjs/helper-numbers->1.11.1, @webassemblyjs/floating-point-hex-parser->1.11.1, @webassemblyjs/helper-api-error->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/helper-wasm-bytecode->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/wasm-parser->1.11.1, @webassemblyjs/ast->1.11.1, @webassemblyjs/helper-numbers->1.11.1, @webassemblyjs/floating-point-hex-parser->1.11.1, @webassemblyjs/helper-api-error->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/helper-api-error->1.11.1, @webassemblyjs/helper-wasm-bytecode->1.11.1, @webassemblyjs/ieee754->1.11.1, @xtuc/ieee754->1.2.0, @webassemblyjs/leb128->1.11.1, @xtuc/long->4.2.2, @webassemblyjs/utf8->1.11.1, acorn->8.5.0, acorn-import-assertions->1.8.0, browserslist->4.17.4, caniuse-lite->1.0.30001270, electron-to-chromium->1.3.873, escalade->3.1.1, node-releases->2.0.0, picocolors->1.0.0, chrome-trace-event->1.0.3, enhanced-resolve->5.8.3, graceful-fs->4.2.8, tapable->2.2.1, es-module-lexer->0.9.3, eslint-scope->5.1.1, esrecurse->4.3.0, estraverse->5.2.0, estraverse->4.3.0, events->3.3.0, glob-to-regexp->0.4.1, graceful-fs->4.2.8, json-parse-better-errors->1.0.2, loader-runner->4.2.0, mime-types->2.1.33, mime-db->1.50.0, neo-async->2.6.2, schema-utils->3.1.1, @types/json-schema->7.0.9, ajv->6.12.6, fast-deep-equal->3.1.3, fast-json-stable-stringify->2.1.0, json-schema-traverse->0.4.1, uri-js->4.4.1, punycode->2.1.1, ajv-keywords->3.5.2, tapable->2.2.1, terser-webpack-plugin->5.2.4, jest-worker->27.3.1, @types/node->16.11.1, merge-stream->2.0.0, supports-color->8.1.1, has-flag->4.0.0, p-limit->3.1.0, yocto-queue->0.1.0, schema-utils->3.1.1, @types/json-schema->7.0.9, ajv->6.12.6, fast-deep-equal->3.1.3, fast-json-stable-stringify->2.1.0, json-schema-traverse->0.4.1, uri-js->4.4.1, punycode->2.1.1, ajv-keywords->3.5.2, serialize-javascript->6.0.0, randombytes->2.1.0, safe-buffer->5.2.1, source-map->0.6.1, terser->5.9.0, commander->2.20.3, source-map->0.7.3, source-map-support->0.5.20, buffer-from->1.1.2, source-map->0.6.1, watchpack->2.2.0, glob-to-regexp->0.4.1, graceful-fs->4.2.8, webpack-sources->3.2.1
Fetching https://registry.npmjs.org/webpack/-/webpack-5.59.0.tgz..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Fetching https://registry.npmjs.org/@types/eslint-scope/-/eslint-scope-3.7.1.tgz...
Traceback (most recent call last):
  File "/usr/lib/python3.9/shutil.py", line 814, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpgi47tjcg/package' -> '[...]/assets_dl/@types/eslint-scope'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/dl_webpack.py", line 3, in <module>
    dukpy.install_jspackage("webpack", "5.59.0", "assets_dl/")
  File "[...]/lib/python3.9/site-packages/dukpy/install.py", line 82, in install_jspackage
    shutil.move(os.path.join(tmpdir, 'package'),
  File "/usr/lib/python3.9/shutil.py", line 834, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.9/shutil.py", line 443, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 265, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpgi47tjcg/package'
```

**Comment by amol-** [comment]
This should be fixed by https://github.com/amol-/dukpy/commit/da8cefb4fbacd45ab9d2f857fe8e1437983fdbbe
