### ISSUE TITLE
Error: cannot find module: path

### ISSUE THREAD

**Issue by Mortal** [amol-/dukpy#8]
I'm trying to run less.js with dukpy, but the library appears to use the [Node.js path module](https://nodejs.org/api/path.html) which seems to be unavailable with dukpy.

Is this fixable?

```
(venv) rav@gonzales:~/dukpy$ dukpy-install less
Packages going to be installed: less->2.7.1, image-size->0.5.0, source-map->0.5.6, graceful-fs->4.1.5, mime->1.3.4, errno->0.1.4, prr->0.0.0, promise->7.1.1, asap->2.0.4, mkdirp->0.5.1, minimist->0.0.8
Fetching https://registry.npmjs.org/promise/-/promise-7.1.1.tgz..........................
Fetching https://registry.npmjs.org/image-size/-/image-size-0.5.0.tgz.......
Fetching https://registry.npmjs.org/asap/-/asap-2.0.4.tgz...........
Fetching https://registry.npmjs.org/source-map/-/source-map-0.5.6.tgz.......................................................................................................................................................................................
Fetching https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.5.tgz........
Fetching https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz......
Fetching https://registry.npmjs.org/prr/-/prr-0.0.0.tgz....
Fetching https://registry.npmjs.org/mime/-/mime-1.3.4.tgz............
Fetching https://registry.npmjs.org/errno/-/errno-0.1.4.tgz......
Fetching https://registry.npmjs.org/less/-/less-2.7.1.tgz...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Fetching https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz.....
Installing less in ./js_modules Done!
(venv) rav@gonzales:~/dukpy$ python
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dukpy.evaljs import evaljs
>>> evaljs('require("less")')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ssd/home/venvs/kasse/lib/python3.5/site-packages/dukpy/evaljs.py", line 119, in evaljs
    return JSInterpreter().evaljs(code, **kwargs)
  File "/ssd/home/venvs/kasse/lib/python3.5/site-packages/dukpy/evaljs.py", line 53, in evaljs
    res = _dukpy.eval_string(self, jscode, jsvars)
_dukpy.JSRuntimeError: Error: cannot find module: less
	anon src/pyduktape.c:5 preventsyield
	require  native strict preventsyield
	eval src/pyduktape.c:1 preventsyield
```

Trying to import the `path` module directly similarly fails:

```
>>> interpreter = dukpy.JSInterpreter()
>>> interpreter.loader.register_path('./js_modules')
>>> interpreter.evaljs('require("path")'
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ssd/home/venvs/kasse/lib/python3.5/site-packages/dukpy/evaljs.py", line 53, in evaljs
    res = _dukpy.eval_string(self, jscode, jsvars)
_dukpy.JSRuntimeError: Error: cannot find module: path
	anon src/pyduktape.c:5 preventsyield
	require  native strict preventsyield
	eval src/pyduktape.c:1 preventsyield
>>> interpreter.evaljs('require("./path")')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ssd/home/venvs/kasse/lib/python3.5/site-packages/dukpy/evaljs.py", line 53, in evaljs
    res = _dukpy.eval_string(self, jscode, jsvars)
_dukpy.JSRuntimeError: Error: cannot find module: path
	anon src/pyduktape.c:5 preventsyield
	require  native strict preventsyield
	eval src/pyduktape.c:1 preventsyield
```

**Comment by amol-** [comment]
DukPY currently is far from implementing the whole NodeJS runtime, apart from require support no other nodejs specific module is provided. 

It might be easier to make a lessc implementation for browsers run on DukPy as they usually do not rely on files, paths, I/O etc... otherwise you might want to contribute an implementation of the path module. As DukPY allows exporting python code it should be fairly quick to replicate a working implementation of nodejs path module based on python `os.path`

**Comment by amol-** [comment]
I successfully run the following snippet:

```
from dukpy import evaljs

COMPILE_LESS = '''
window={};
window.document={};
window.document.getElementsByTagName = function(tagname) { if(tagname === "head") return [{}]; else return []; }

less = require("./less.js");
less.render("p{color: #ff66ff}", {}, function(error, output) {
    print(output.css);
});
'''

res = evaljs([COMPILE_LESS])
```

Using a slightly modified version of less.js ( see attached [less.js.txt](https://github.com/amol-/dukpy/files/405530/less.js.txt) )

The changes are mostly related to removing references to `window.location`, `setInterval` and setting `options.onReady=false`  as there is no DOM in dukpy to convert. Probably all changes that can be prepared before calling the less.js

So far it's only an experiment to check if it's possible, more refactoring and cleanup to avoid the need to modify the original `less.js` file is required before being able to include this into dukpy.

**Comment by amol-** [comment]
https://github.com/amol-/dukpy/commit/3e19b313430066c717f5024b1f4c120cdbe0ede3 provides a working `dukpy.less_compile` function that is able to compile less with support for `@import` through a minimal nodejs compatibility layer.

**Comment by Mortal** [comment]
Thank you so much!
